name       : fritzing-parts
version    : 10052022 # Date of the latest commit formatted as ddmmyyyy
release    : 5
source     :
    # This must be a git clone according to: https://github.com/fritzing/fritzing-app/wiki/2.1-Part-file-format
    # Make sure to use a commit in the master branch. The default branch is develop.
    - git|https://github.com/fritzing/fritzing-parts.git : 4713511c894cb2894eae505b9307c6555afcc32c
license    : CC-BY-SA-3.0
component  : programming
summary    : Fritzing parts
description: |
    Fritzing data file of supplemental parts.
builddeps  :
    - fritzing
install    : |
    install -dm00755 $installdir/usr/share/fritzing
    cp -a $sources/fritzing-parts.git $installdir/usr/share/fritzing/fritzing-parts

    # Build the parts database.
    Fritzing \
        -f /usr/share/fritzing \
        -pp $installdir/usr/share/fritzing/fritzing-parts \
        -db $installdir/usr/share/fritzing/fritzing-parts/parts.db \
        -platform offscreen

    # Remove unnecessary files
    rm -r $installdir/usr/share/fritzing/fritzing-parts/.git*
    rm $installdir/usr/share/fritzing/fritzing-parts/*.md
    rm $installdir/usr/share/fritzing/fritzing-parts/*.txt
