name       : fritzing-parts
version    : 22092019 # Date of the latest commit formatted as ddmmyyyy
release    : 3
source     :
    # This must be a git clone according to: https://github.com/fritzing/fritzing-app/wiki/2.1-Part-file-format
    # Make sure to use a commit in the master branch. The default branch is develop.
    - git|https://github.com/fritzing/fritzing-parts.git : e79a69765026f3fda8aab1b3e7a4952c28047a62
license    : CC-BY-SA-3.0
component  : programming
summary    : Fritzing parts
description: |
    Fritzing data file of supplemental parts.
builddeps  :
    - fritzing
install    : |
    install -dm00755 $installdir/usr/share/fritzing
    cp -a $sources/fritzing-parts.git $installdir/usr/share/fritzing/fritzing-parts

    # Build the parts database.
    Fritzing \
        -f /usr/share/fritzing \
        -pp $installdir/usr/share/fritzing/fritzing-parts \
        -db $installdir/usr/share/fritzing/fritzing-parts/parts.db \
        -platform offscreen
