name       : fritzing-parts
version    : 0.9.3b
release    : 1
source     :
    - https://github.com/fritzing/fritzing-parts/archive/0.9.3b.tar.gz : c40a9a50df0af78905968792b2ce595896af1935633600d6136eca0cf9797fdb
license    : CC-BY-SA-3.0
component  : programming
summary    : Fritzing parts
description: |
    Fritzing data file of supplemental parts
install    : |
    mkdir -p $installdir/usr/share/fritzing/parts
    cp -R * $installdir/usr/share/fritzing/parts/
    chmod -R 644 $installdir/usr/share/fritzing/parts/*
